// <auto-generated />
namespace ECommerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class all_Database_ECommerce : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(all_Database_ECommerce));
        
        string IMigrationMetadata.Id
        {
            get { return "201811221754098_all_Database_ECommerce"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
